variable "instance_type" {
  type        = string
  description = "The type of instance to launch"
  default     = "t3.micro"
}

variable "subnet_id" {
  type        = string
  description = "The ID of the subnet to launch the instance into"

  validation {
    condition     = length(regexall("^subnet-[\\d|\\w]+$", var.subnet_id)) == 1
    error_message = "The subnet ID must match the pattern ^subnet-[\\d|\\w]+$"
  }
}

variable "name_prefix" {
  type        = string
  description = "The prefix to apply to names generated by this module"
}

variable "tags" {
  type        = map(string)
  description = "Key/value pairs to pass as tags to aws"
  default     = {}
}

variable "instance_count" {
  type        = number
  description = "Number of instances to launch"
  default     = 0
  validation {
    condition     = var.instance_count >= 0
    error_message = "must not be negative"
  }
  validation {
    condition     = can(parseint(var.instance_count, 10))
    error_message = "must not have a fractional part"
  }
}